region_healthcare_EnviromentCleaning_path: 'Data\region_healthcare_EnviromentCleaning.csv'
region_healthcare_hygiene_path: 'Data\region_healthcare_hygiene.csv'
region_healthcare_sanitation_path: 'Data\region_healthcare_sanitation.csv'
region_healthcare_WasteManagement_path: 'Data\region_healthcare_WasteManagement.csv'
region_healthcare_water_path: 'Data\region_healthcare_water.csv'
region_household_hygiene_path: 'Data\region_household_hygiene.csv'
region_household_sanitatione_path: 'region_houshold_sanitation.csv'
region_household_water_path: 'region_houshold_water.csv'
region_school_hygine_path: 'Data\region_school_hygine.csv'
region_school_sanitation_path: 'Data\region_school_sanitation.csv'
region_school_water_path: 'Data\region_school_water.csv'
world_healthcare_EnvironmentCleaning_path: 'Data\world_healthcare_EnvironmentCleaning.csv'
world_healthcare_hygiene_path: 'Data\world_healthcare_hygiene.csv'
world_healthcare_sanitation_path: 'Data\world_healthcare_sanitation.csv'
world_healthcare_WasteManagement_path: 'Data\world_healthcare_WasteManagement.csv'
world_healthcare_water_path: 'Data\world_healthcare_water.csv'
world_household_hygiene_path: 'Data\world_household_hygiene.csv'
world_household_menstural_path: 'Data\world_household_menstural.csv'
world_household_sanitation_path: 'Data\world_household_sanitation.csv'
world_household_water_path: 'Data\world_household_water.csv'
world_school_wash_path: 'Data\world_school_wash.csv'


